{"componentChunkName":"component---src-templates-mdx-index-js","path":"/posts/javascript-environment-part-five/","result":{"data":{"mdx":{"id":"579ac86d-3d11-55d1-b361-6dd7aaf92eee","body":"function _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }\n\nfunction _objectWithoutProperties(source, excluded) { if (source == null) return {}; var target = _objectWithoutPropertiesLoose(source, excluded); var key, i; if (Object.getOwnPropertySymbols) { var sourceSymbolKeys = Object.getOwnPropertySymbols(source); for (i = 0; i < sourceSymbolKeys.length; i++) { key = sourceSymbolKeys[i]; if (excluded.indexOf(key) >= 0) continue; if (!Object.prototype.propertyIsEnumerable.call(source, key)) continue; target[key] = source[key]; } } return target; }\n\nfunction _objectWithoutPropertiesLoose(source, excluded) { if (source == null) return {}; var target = {}; var sourceKeys = Object.keys(source); var key, i; for (i = 0; i < sourceKeys.length; i++) { key = sourceKeys[i]; if (excluded.indexOf(key) >= 0) continue; target[key] = source[key]; } return target; }\n\n/* @jsx mdx */\nvar _frontmatter = {\n  \"title\": \"The JavaScript Environment Part Five - Asynchronous Operations\",\n  \"date\": \"2020-08-12T00:00:00.000Z\"\n};\n\nvar makeShortcode = function makeShortcode(name) {\n  return function MDXDefaultShortcode(props) {\n    console.warn(\"Component \" + name + \" was not imported, exported, or provided by MDXProvider as global scope\");\n    return mdx(\"div\", props);\n  };\n};\n\nvar Link = makeShortcode(\"Link\");\nvar layoutProps = {\n  _frontmatter: _frontmatter\n};\nvar MDXLayout = \"wrapper\";\nreturn function MDXContent(_ref) {\n  var components = _ref.components,\n      props = _objectWithoutProperties(_ref, [\"components\"]);\n\n  return mdx(MDXLayout, _extends({}, layoutProps, props, {\n    components: components,\n    mdxType: \"MDXLayout\"\n  }), mdx(\"p\", null, \"This is part five of a five part series I\\u2019ve written to assist in my learning, and also to help anyone else out there facing similar struggles. Check out the other parts of this series:\"), mdx(\"ol\", null, mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(Link, {\n    to: \"/posts/javascript-environment-part-one\",\n    mdxType: \"Link\"\n  }, \"Overview\")), mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(Link, {\n    to: \"/posts/javascript-environment-part-two\",\n    mdxType: \"Link\"\n  }, \"JavaScript engines\")), mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(Link, {\n    to: \"/posts/javascript-environment-part-three\",\n    mdxType: \"Link\"\n  }, \"Closures\")), mdx(\"li\", {\n    parentName: \"ol\"\n  }, mdx(Link, {\n    to: \"/posts/javascript-environment-part-four\",\n    mdxType: \"Link\"\n  }, \"Browser engines\")), mdx(\"li\", {\n    parentName: \"ol\"\n  }, \"Asynchronous Operations\")), mdx(\"h2\", null, \"Asynchronous Operations\"), mdx(\"h3\", null, \"Overview\"), mdx(\"p\", null, \"JavaScript applications use a single threaded execution model; the event loop is also therefore single threaded. As a result, long running operations on the call stack will block the UI from updating. Thankfully, most long running operations run asynchronously, or in other words on a separate thread from the event loop, through Web APIs built into the browser. \"), mdx(\"p\", null, \"While these APIs can be accessed through functions available in JavaScript (e.g. \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"fetch()\"), \"), these functions aren\\u2019t called synchronously like other JavaScript functions because this would force the function to remain on the call stack until the API to returns, once again blocking the event loop and therefore the UI from updating. Instead, when these functions are called, their references are immediately removed from the call stack until their API returns, at which point a new function is added to the call stack which contains all code to be executed on the API\\u2019s completion. \"), mdx(\"p\", null, \"It\\u2019s important to note that not all Web APIs handle asynchronous operations in the same way because of evolutions in ECMAScript standards over time. Some functions (e.g. \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"XMLHttpRequest()\"), \") even have their own methods of handling this behavior. \"), mdx(\"h3\", null, \"Callback Functions\"), mdx(\"p\", null, \"Web APIs written before ES2015 often handled asynchronous operations through \", mdx(\"em\", {\n    parentName: \"p\"\n  }, \"callback functions\"), \", or functions passed into another function as an argument, with the intent of being called back at a later point in time. These functions are called on the return of the Web API. \"), mdx(\"p\", null, \"The following examples use JQuery\\u2019s \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"getJSON()\"), \" function. \"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"$.getJSON(\\\"./example.json\\\", function(){\\n  // handle results \\n});\\n\")), mdx(\"p\", null, \"Unfortunately this method has many problems, namely the following:\"), mdx(\"h4\", null, \"Error handling\"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"try {\\n  $.getJSON(\\\"./example.json\\\", function(result){\\n    const data = JSON.parse(result);\\n  });\\n} catch(error){\\n  // handle errors\\n}\\n\")), mdx(\"p\", null, \"In this block, the callback function is called on an entirely different iteration of the event loop and is the only function on the call stack. If an error is thrown within it, for example from the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"JSON.parse()\"), \" call, the catch block will not be called and the error will be lost. \"), mdx(\"h4\", null, \"The Pyramid of Doom\"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"$.getJSON(\\\"./example1.json\\\", function(){\\n  $.getJSON(\\\"./example2.json\\\", function(){\\n    $.getJSON(\\\"./example3.json\\\", function(){\\n      // handle results \\n    });\\n  });\\n});\\n\")), mdx(\"p\", null, \"Calling asynchronous functions in the callback of other asynchronous function results in very difficult code. \"), mdx(\"h4\", null, \"Running Asynchronous Functions in Parallel\"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"$.getJSON(\\\"./example1.json\\\", function(){\\n  // handle results \\n});\\n$.getJSON(\\\"./example2.json\\\", function(){\\n  // handle results \\n});\\n$.getJSON(\\\"./example3.json\\\", function(){\\n  // handle results \\n});\\n\")), mdx(\"p\", null, \"In this case, there is no way to know when all the callbacks have returned. If there is some operation that should be completed after all have returned, the only way to know when it should run would be to check if every asynchronous function has returned in every callback. \"), mdx(\"p\", null, mdx(\"strong\", {\n    parentName: \"p\"\n  }, \"Note:\"), \" \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"getJSON()\"), \" is a JQuery function. \"), mdx(\"h3\", null, \"Promises\"), mdx(\"p\", null, \"Web APIs written after ES2015 handle asynchronous operations through \", mdx(\"em\", {\n    parentName: \"p\"\n  }, \"Promises\"), \". \"), mdx(\"p\", null, \"A promise is a placeholder object for a value that doesn\\u2019t exist, but might in the future. If the promise is kept, its result will be a value. Otherwise, its result will be an error. \"), mdx(\"p\", null, \"Promises have three states:\"), mdx(\"ul\", null, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"pending, or unresolved state: The value is completely unknown. \"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"fulfilled state: The promise\\u2019s \", mdx(\"inlineCode\", {\n    parentName: \"li\"\n  }, \"resolve()\"), \" function has been called and the promised value has been returned. \"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"rejected state: \", mdx(\"ul\", {\n    parentName: \"li\"\n  }, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"The promise\\u2019s \", mdx(\"inlineCode\", {\n    parentName: \"li\"\n  }, \"reject()\"), \" function has been called\"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"an unhandled exception occurred\")))), mdx(\"p\", null, \"The promise is considered resolved if it has entered either the fulfilled or rejected state. \"), mdx(\"p\", null, mdx(\"strong\", {\n    parentName: \"p\"\n  }, \"Note:\"), \" The resolve and reject functions are called by the promise in response to some event that should result in the promise being fulfilled or rejected. The promise callback is for reacting to the promise being fulfilled or rejected.   \"), mdx(\"h4\", null, \"Creating promises\"), mdx(\"p\", null, \"The promise constructor takes a single function with resolve and reject functions as parameters, which are provided when the promise is used. This function is called the executor, which is immediately invoked. \"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"const promise = new Promise((resolve, reject) => {\\n  resolve(\\\"result\\\");\\n  // reject(\\\"error\\\");\\n});\\n\\n\")), mdx(\"h4\", null, \"Using promises\"), mdx(\"p\", null, \"Promises are used by calling their built in \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"then()\"), \" method. This method takes two callback functions: a resolve and a reject. The resolve function is called if the promise should be fulfilled, and the reject function is called if an error occurs.  \"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"promise.then(result => {\\n  console.log(result);\\n}, error => {\\n  console.log(error);\\n});\\n\")), mdx(\"p\", null, mdx(\"strong\", {\n    parentName: \"p\"\n  }, \"Note:\"), \" The \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"then()\"), \" callback is added to the microtask queue, so it is run after all code in the current step of the event loop has completed. \"), mdx(\"p\", null, mdx(\"strong\", {\n    parentName: \"p\"\n  }, \"Example:\"), \" The setTimeout Web API uses callbacks to handle its asynchronous operation. Fortunately, can wrap it in a promise to make it easier to work with. \"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"function setTimeoutPromise(time) {\\n  return new Promise((resolve, reject) => {\\n    id = setTimeout(() => {\\n      resolve(id);\\n    }, time);\\n  });\\n}\\n\\nsetTimeoutPromise(1000).then(id => {\\n  console.log(id);\\n});\\n\")), mdx(\"h4\", null, \"Rejecting promises\"), mdx(\"p\", null, \"Promises can be rejected in two ways: \"), mdx(\"ul\", null, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"Explicitly: by calling reject in the executor function. \"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"Implicitly: if an unhandled exception occurs, for example an undeclared variable. \")), mdx(\"p\", null, \"In either of these circumstances, the reject callback of the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"then()\"), \" function will be called. \"), mdx(\"h4\", null, \"Chaining promises\"), mdx(\"p\", null, \"Then \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"then()\"), \" method always returns a new promise. As it turns out, this is useful in cases where a future promise depends on the success of a previous promise;its possible to chain promises together to run one after another!  \"), mdx(\"p\", null, \"In this case its better to omit the failure callback and handle errors after the final promise in a catch statement. In case of an error, the catch statement will immediately be invoked and the chain will be broken. \"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"getJSON(data/resultA.json)\\n.then(resultA => getJSON(data/resultB.json))\\n.then(resultB => console.log(\\\"completed chain\\\"))\\n.catch(error => console.log(error));\\n\")), mdx(\"p\", null, mdx(\"strong\", {\n    parentName: \"p\"\n  }, \"Note:\"), \" Even in the case of a single promise, a catch statement can be used to handle errors as opposed to the reject function. \"), mdx(\"h4\", null, \"Waiting for a number of promises\"), mdx(\"p\", null, \"If we don\\u2019t care about the order the promises are completed, we can use the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Promise.all()\"), \" method. This method takes an array full of function callbacks, the promise callback receives an array of all fulfilled values. This promise will fail if any of the promises in it fails. \"), mdx(\"p\", null, \"If we only care about the first promise to be completed, we can call \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Promise.race()\"), \". It operates the same as \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"Promise.all()\"), \", except it returns a new promise that fulfills or rejects based only on the first promise to fulfill or reject. \"), mdx(\"h3\", null, \"Async/Await\"), mdx(\"p\", null, \"ES2017 introduced the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"async\"), \" and \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"await\"), \" keywords to simplify writing promises in a synchronous way. At a high level, \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"async\"), \" and \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"await\"), \" essentially operate as a way to combine ES2015 generator functions and promises. \"), mdx(\"p\", null, \"Remember, yielding from a generator function pauses its execution without blocking the call stack. Combining this ability with promises makes it possible to pause execution of a function containing a promise until the promise has been resolved and its \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"then()\"), \" method has been called. \"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"function setTimeoutPromise(time) {\\n  return new Promise((resolve, reject) => {\\n    id = setTimeout(() => {\\n      resolve(id);\\n    }, time);\\n  });\\n}\\n\\nasync function doubleTimeout(time) { \\n  firstId = await setTimeoutPromise(time);\\n  secondId = await setTimeoutPromise(time);\\n  return [firstId, secondId];\\n};\\n\")), mdx(\"p\", null, \"In this example, the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"async\"), \" keyword defines the function as an asynchronous function, and the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"await\"), \" keyword followed by an asynchronous operation \", mdx(\"em\", {\n    parentName: \"p\"\n  }, \"that returns a promise\"), \", creates an expression that pauses the function\\u2019s execution until the promise is resolved. \"), mdx(\"p\", null, \"Async functions always return promises. If some value other than a promise is returned, it is wrapped in a promise. For this reason, the result of the function must be accessed through the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"then()\"), \" method. \"), mdx(\"h4\", null, \"Error handling\"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"function getJSONPromise(path) {\\n  return new Promise((resolve, reject) => {\\n    $.getJSON(() => {\\n      resolve(path);\\n    });\\n  });\\n}\\n\\ntry {\\n  getJSONPromise(\\\"./example.json\\\")\\n    .then(function(result) {\\n      const data = JSON.parse(result);\\n    });\\n} catch(error){\\n  // handle errors\\n}\\n\")), mdx(\"p\", null, \"Notice that promises have the same error handling issues that callback functions have. Once again, the callback function in the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"then()\"), \" method is called on an entirely different iteration of the event loop and is the only function on the call stack. If an error is thrown within it, for example from the \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"JSON.parse()\"), \" call, the catch block will not be called and the error will be lost. \"), mdx(\"p\", null, \"With \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"async\"), \" and \", mdx(\"inlineCode\", {\n    parentName: \"p\"\n  }, \"await\"), \", however, the catch statement actually will catch the error. \"), mdx(\"pre\", null, mdx(\"code\", _extends({\n    parentName: \"pre\"\n  }, {}), \"async function getJSONAsync() {\\n  try {\\n    const data = JSON.parse(await $.getJSON());\\n  }\\n  catch(error) {\\n    console.log(error);\\n  }\\n}\\n\")), mdx(\"h4\", null, \"Error Reporting\"), mdx(\"p\", null, \"Promises report all errors, \", mdx(\"em\", {\n    parentName: \"p\"\n  }, \"even those within \", mdx(\"inlineCode\", {\n    parentName: \"em\"\n  }, \"then()\")), \" calls, as originating within the promise itself. This makes it very difficult to track down where an error originates from because a function that returns a new promise could be called throughout the code base and handle errors differently each time. \"), mdx(\"p\", null, \"In async functions, errors are reported as coming from the function where they originate. \"), mdx(\"h4\", null, \"Syntax\"), mdx(\"p\", null, \"Async functions improve syntax significantly from promises. \"), mdx(\"ul\", null, mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"conditionally chained promises do not require nested \", mdx(\"inlineCode\", {\n    parentName: \"li\"\n  }, \"then()\"), \" calls like promise chains do. \"), mdx(\"li\", {\n    parentName: \"ul\"\n  }, \"synchronously called async operations do not need complicated \", mdx(\"inlineCode\", {\n    parentName: \"li\"\n  }, \"then()\"), \" calls like promise chains do. \")));\n}\n;\nMDXContent.isMDXComponent = true;","fileAbsolutePath":"/home/lee/projects/gatsby/data-viz-portfolio/src/content/posts/javascript-environment-part-five.mdx","frontmatter":{"title":"The JavaScript Environment Part Five - Asynchronous Operations","date":"August 12, 2020"}}},"pageContext":{"id":"579ac86d-3d11-55d1-b361-6dd7aaf92eee"}}}